import type { LLMResponse } from "../models/llm-response";

export function buildEvaluationPrompt(
  question: string,
  responses: LLMResponse[],
): string {
  const formattedResponses = responses
    .filter((response) => !response.error)
    .map(
      (response, index) => `
### Response ${index + 1}

Provider: ${response.provider}
Model: ${response.model}

${response.content.trim()}
`,
    )
    .join("\n---\n");

  return `
User Question:

${question}

Below are the responses generated by different AI models.

${formattedResponses}

Generate the best possible final answer.
`.trim();
}